site_name: Sigmapedia
site_url: https://sigmism.surge.sh/sigmapedia
repo_url: https://github.com/The-Church-of-Sigma/Sigmapedia/
repo_name: Sigmapedia GitHub Repo
edit_uri: edit/main/docs/
nav:
  - Welcome!: index.md

  - Concepts & Terms: 
    - concepts/index.md
    - Among Us: concepts/among-us.md
    - Fire in the Hole: concepts/fire-in-the-hole.md
    - Goofy: concepts/goofy.md
    - Gyatt: concepts/gyatt.md
    - Mewing: concepts/mewing.md
    - Rizz: concepts/rizz.md
    - Meta: 
      - concepts/meta/index.md
      - Sigmapedia: concepts/meta/sigmapedia.md

  - Entities & People:
    - Baby Gronk: entities/baby-gronk.md
    - DaFuq!?Boom!: entities/dafuq-boom.md

  - Places:
    - places/index.md

  - Scriptures:
    - scriptures/index.md

  - Traditions & Conventions:
    - traditions/index.md
  
theme:
  name: 'material'
  custom_dir: overrides
  font:
    text: Poppins
    code: Kode Mono
  palette:
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/sigma.png
  favicon: assets/sigma.png
  markdown_extensions:
  features:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
extra:
  generator: false
  consent:
    title: Cookie consent
    description:
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our wiki and whether our Siglers
      find what they're searching for. With your consent, you're helping us to
      make our wiki and our religion better.
  homepage: https://sigmism.surge.sh
plugins:
  - search
  - git-revision-date-localized:
      type: date
markdown_extensions:
  - attr_list
  - md_in_html