name: Deploy MkDocs to website repo

on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin

      - name: Build the MkDocs site
        run: mkdocs build

      - name: Checkout the target repo
        uses: actions/checkout@v2
        with:
          repository: The-Church-of-Sigma/Website
          path: website-repo
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Copy the built site
        run: |
          rm -rf website-repo/sigmapedia/*
          cp -r site/* website-repo/sigmapedia/

      - name: Commit and push changes
        run: |
          cd website-repo
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Deploy Sigmapedia from separate repo"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
